# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gina Helfrich, Ph.D
email: gina.helfrich@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Diversity & inclusion expert, communications professional, nonprofit & higher education administrator. Women's leadership and gender equity. Austin, TX.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "https://Dr-G.github.io" # the base hostname & protocol for your site
twitter_username: ginahelfrich
github_username:  Dr-G
linkedin_username: ginahelfrich

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
